version: "3.8"

services:
  churn-api:
    build: .
    container_name: churn_prediction_api
    ports:
      - "8000:8000"
    volumes:
      - ./model:/app/model
    restart: unless-stopped